# Generated by Django 4.1.2 on 2022-11-17 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='opposingTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opposed_team', to='hockey.team', verbose_name='Equipe adverse'),
        ),
    ]
