# Generated by Django 4.1.2 on 2022-11-17 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0002_match_opposingteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='assistant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant', to='hockey.player', verbose_name='Assistant'),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='hockey.player', verbose_name='Capitaine '),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='hockey.player', verbose_name='Coach'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom de l'equipe"),
        ),
        migrations.AlterField(
            model_name='team',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='hockey.player', verbose_name='Entreneur'),
        ),
    ]
