# Generated by Django 4.1.2 on 2022-10-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0002_alter_user_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joueur',
            old_name='user_id',
            new_name='user',
        ),
    ]
