# Generated by Django 4.1.2 on 2022-10-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0003_rename_user_id_joueur_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joueur',
            old_name='location',
            new_name='nationality',
        ),
    ]
