# Generated by Django 4.1.2 on 2022-10-16 15:22

from django.db import migrations
import django_countries.fields
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0004_rename_location_joueur_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joueur',
            name='country',
        ),
        migrations.AddField(
            model_name='joueur',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
