# Generated by Django 4.1.2 on 2022-10-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0005_remove_joueur_country_joueur_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joueur',
            old_name='nationality',
            new_name='country',
        ),
    ]
