# Generated by Django 4.1.2 on 2022-10-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0006_rename_nationality_joueur_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joueur',
            name='birthday_dayofyear_internal',
        ),
        migrations.RemoveField(
            model_name='joueur',
            name='country',
        ),
        migrations.AddField(
            model_name='joueur',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='phone',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
    ]
