# Generated by Django 4.1.2 on 2022-10-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0007_remove_joueur_birthday_dayofyear_internal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
