# Generated by Django 4.1.2 on 2022-10-17 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0009_joueur_height_joueur_weigth_alter_joueur_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='isMe',
            field=models.BooleanField(default=True, verbose_name="C'est moi"),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='birthday',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='height',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(100)], verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nationalite'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='weigth',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(200)], verbose_name='Poids'),
        ),
    ]
