# Generated by Django 4.1.2 on 2022-10-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0011_joueur_manualpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='playerRole',
            field=models.CharField(blank=True, choices=[(1, 'Allié droite'), (2, 'Allié gauche'), (3, 'Centre'), (4, 'Défenseur droit'), (5, 'Défenseur gauche'), (6, 'Goalkeeper')], max_length=20, null=True, verbose_name='Role'),
        ),
    ]
