# Generated by Django 4.1.2 on 2022-10-19 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0012_joueur_playerrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='weigth',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(200)], verbose_name='Poids'),
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ManyToManyField(to='hockey.joueur', verbose_name='Joueur')),
            ],
        ),
    ]
