# Generated by Django 4.1.2 on 2022-10-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0013_alter_joueur_weigth_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='nameEquipe',
            field=models.CharField(blank=True, max_length=30, verbose_name="Nom de l'equipe"),
        ),
    ]
