# Generated by Django 4.1.2 on 2022-10-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0014_equipe_nameequipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='licence',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
