# Generated by Django 4.1.2 on 2022-10-19 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0015_joueur_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/photosEquipes', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
