# Generated by Django 4.1.2 on 2022-10-20 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0016_equipe_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='nameEquipe',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='equipe',
            old_name='player',
            new_name='players',
        ),
        migrations.AddField(
            model_name='equipe',
            name='assistant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='assistant', to='hockey.joueur', verbose_name='Assistant'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='captain',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='captain', to='hockey.joueur', verbose_name='Capitaine '),
        ),
        migrations.AddField(
            model_name='equipe',
            name='coach',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='coach', to='hockey.joueur', verbose_name='Coach'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name="Code de l'equipe"),
        ),
        migrations.AddField(
            model_name='equipe',
            name='maxAge',
            field=models.IntegerField(blank=True, null=True, verbose_name="L'age maximal"),
        ),
        migrations.AddField(
            model_name='equipe',
            name='minAge',
            field=models.IntegerField(blank=True, null=True, verbose_name="L'age minimal"),
        ),
        migrations.AddField(
            model_name='equipe',
            name='trainer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='trainer', to='hockey.joueur', verbose_name='Entreneur'),
        ),
    ]
