# Generated by Django 4.1.2 on 2022-10-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0017_rename_nameequipe_equipe_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Joueur',
            new_name='Player',
        ),
        migrations.RenameModel(
            old_name='Equipe',
            new_name='Team',
        ),
    ]
