# Generated by Django 4.1.2 on 2022-10-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0019_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[(1, '(*) RDV 1h15 avant pour la séance'), (2, '(**) shooters sur convocation'), (3, 'HG = Hors Glace')], max_length=200, verbose_name='Jour')),
            ],
        ),
    ]
