# Generated by Django 4.1.2 on 2022-10-21 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0020_specialinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='specialInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hockey.specialinfo'),
        ),
    ]
