# Generated by Django 4.1.2 on 2022-10-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0021_timetable_specialinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialinfo',
            name='description',
            field=models.CharField(choices=[(1, '(*) RDV 1h15 avant pour la séance'), (2, '(**) shooters sur convocation'), (3, 'HG = Hors Glace')], max_length=200, verbose_name='Informations spéciales'),
        ),
    ]
