# Generated by Django 4.1.2 on 2022-10-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0022_alter_specialinfo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractMoralEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/AbstractMoralEntity_files')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('link', models.URLField(verbose_name='Link')),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='licence',
            field=models.FileField(blank=True, null=True, upload_to='uploads/Player_files'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/Team_files'),
        ),
    ]
