# Generated by Django 4.1.2 on 2022-10-23 16:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0025_club_alter_player_user_alter_timetable_team_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('link', models.URLField(verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Rink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(regex='^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$')], verbose_name='Telephone')),
                ('localisation', models.CharField(blank=True, max_length=30, verbose_name='Localisation')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse mail')),
                ('link', models.URLField(verbose_name='Link')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='atHome',
            field=models.BooleanField(default=True, verbose_name='Match à la maison?'),
        ),
        migrations.AddField(
            model_name='match',
            name='dateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure du match'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moralEntity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hockey.abstractmoralentity', verbose_name='Entité morale associe')),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ourScore', models.IntegerField(blank=True, null=True, verbose_name="Score de l'equipe maison")),
                ('theirScore', models.IntegerField(blank=True, null=True, verbose_name="Score de l'equipe adverse")),
                ('matchPaper', models.FileField(blank=True, null=True, upload_to='uploads/MatchResult_files', verbose_name='Feuille de match')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hockey.match', verbose_name='Match')),
            ],
        ),
    ]
